import Head from 'next/head'
import React from 'react'

function Home() {
  return (
    <>  
        <Head>
            <title>Anka Relief</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>Home</div>
    </>
  )
}

export default Home